//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Id { get; set; }
        public string Users { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<System.DateTime> Lasttime { get; set; }
        public string LastIp { get; set; }
        public Nullable<int> RolId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual Admin Admin1 { get; set; }
        public virtual Admin Admin2 { get; set; }
    }
}
