//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUser
    {
        public BUser()
        {
            this.CBGToB = new HashSet<CBGToB>();
            this.NaturalInfo = new HashSet<NaturalInfo>();
        }
    
        public string Id { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string ShopId { get; set; }
        public string ParentId { get; set; }
        public string ProxyId { get; set; }
        public string PayId { get; set; }
        public string RolId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ProxyUser ProxyUser { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<CBGToB> CBGToB { get; set; }
        public virtual ICollection<NaturalInfo> NaturalInfo { get; set; }
    }
}
