//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBGToB
    {
        public string Id { get; set; }
        public string CUserId { get; set; }
        public string BUserId { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual BUser BUser { get; set; }
        public virtual CommonUser CommonUser { get; set; }
    }
}
