//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonUser
    {
        public CommonUser()
        {
            this.CBGToB = new HashSet<CBGToB>();
            this.CUserEqpt = new HashSet<CUserEqpt>();
            this.Distribution = new HashSet<Distribution>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegistTime { get; set; }
        public Nullable<int> RegistWay { get; set; }
        public string ParentID { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> CashBlance { get; set; }
        public string PayId { get; set; }
        public Nullable<bool> isFreeze { get; set; }
        public Nullable<decimal> FreezeMoney { get; set; }
        public Nullable<int> integral { get; set; }
        public Nullable<bool> IsDistribution { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastIp { get; set; }
        public string NickName { get; set; }
        public string HeadImage { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ICollection<CBGToB> CBGToB { get; set; }
        public virtual ICollection<CUserEqpt> CUserEqpt { get; set; }
        public virtual ICollection<Distribution> Distribution { get; set; }
    }
}
