//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menus
    {
        public menus()
        {
            this.role_menu = new HashSet<role_menu>();
        }
    
        public string menu_id { get; set; }
        public string menu_code { get; set; }
        public string menu_name { get; set; }
        public string menu_url { get; set; }
        public Nullable<int> menu_parentid { get; set; }
        public Nullable<int> menu_order { get; set; }
        public string menu_identity { get; set; }
        public Nullable<int> menu_level { get; set; }
        public Nullable<int> menu_action { get; set; }
        public Nullable<int> menu_app { get; set; }
    
        public virtual ICollection<role_menu> role_menu { get; set; }
    }
}
