//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaturalInfo
    {
        public NaturalInfo()
        {
            this.BrandImprove = new HashSet<BrandImprove>();
        }
    
        public string Id { get; set; }
        public string BUserId { get; set; }
        public string MngName { get; set; }
        public string MngEmail { get; set; }
        public string IDCard { get; set; }
        public string LinkName { get; set; }
        public string LinkMobile { get; set; }
        public string LgName { get; set; }
        public string LgEmail { get; set; }
        public string LgMobile { get; set; }
        public string CompName { get; set; }
        public string Address { get; set; }
        public string LienceCode { get; set; }
        public string OrgCode { get; set; }
        public string TaxCode { get; set; }
        public string CreditCode { get; set; }
        public string IDFront { get; set; }
        public string IDBack { get; set; }
        public Nullable<System.DateTime> IDSDate { get; set; }
        public Nullable<System.DateTime> IDEDate { get; set; }
        public string Licence { get; set; }
        public Nullable<System.DateTime> LceSDate { get; set; }
        public Nullable<System.DateTime> LceEDate { get; set; }
        public string TaxImProve { get; set; }
        public string OrgImProve { get; set; }
        public Nullable<System.DateTime> OrgSDate { get; set; }
        public Nullable<System.DateTime> OrgEDate { get; set; }
        public string OpenAllow { get; set; }
        public Nullable<int> ProxyState { get; set; }
        public Nullable<int> State { get; set; }
        public string refuseReason { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<BrandImprove> BrandImprove { get; set; }
        public virtual BUser BUser { get; set; }
    }
}
