//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProxyNature_c
    {
        public string Id { get; set; }
        public string ProxyUserId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string IDFront { get; set; }
        public string IDBack { get; set; }
        public Nullable<System.DateTime> IDSDate { get; set; }
        public Nullable<System.DateTime> IDEDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
