//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProxyUser
    {
        public ProxyUser()
        {
            this.BUser = new HashSet<BUser>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RegionId { get; set; }
        public Nullable<int> Level { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> RolId { get; set; }
        public string PayId { get; set; }
        public Nullable<decimal> Blance { get; set; }
        public Nullable<decimal> CashBlance { get; set; }
        public string MngName { get; set; }
        public string MngEmail { get; set; }
        public string MngMobile { get; set; }
        public string IDCard { get; set; }
        public string LinkName { get; set; }
        public string LinkMobile { get; set; }
        public string LgName { get; set; }
        public string LgEmail { get; set; }
        public string LgMobile { get; set; }
        public string CompName { get; set; }
        public string Address { get; set; }
        public string LienceCode { get; set; }
        public string OrgCode { get; set; }
        public string TaxCode { get; set; }
        public string CreditCode { get; set; }
        public string IDFront { get; set; }
        public string IDBack { get; set; }
        public Nullable<System.DateTime> IDSDate { get; set; }
        public Nullable<System.DateTime> IDEDate { get; set; }
        public string Licence { get; set; }
        public Nullable<System.DateTime> LceSDate { get; set; }
        public Nullable<System.DateTime> LceEDate { get; set; }
        public string TaxImProve { get; set; }
        public string OrgImProve { get; set; }
        public Nullable<System.DateTime> OrgSDate { get; set; }
        public Nullable<System.DateTime> OrgEDate { get; set; }
        public string OpenAllow { get; set; }
        public Nullable<int> State { get; set; }
        public string refuseReason { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<BUser> BUser { get; set; }
    }
}
