//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopScore
    {
        public string Id { get; set; }
        public string ShopId { get; set; }
        public Nullable<int> Service { get; set; }
        public Nullable<int> ServiceCount { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> QualityCount { get; set; }
        public Nullable<int> SdSpeed { get; set; }
        public Nullable<int> SdCount { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
