//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.BUser = new HashSet<BUser>();
            this.ShopScore = new HashSet<ShopScore>();
        }
    
        public string Id { get; set; }
        public string CgyId { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Introduce { get; set; }
        public Nullable<decimal> Blance { get; set; }
        public Nullable<decimal> CashBlance { get; set; }
        public Nullable<decimal> bail { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual ICollection<BUser> BUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<ShopScore> ShopScore { get; set; }
    }
}
