//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TiDiHuiEntities : DbContext
    {
        public TiDiHuiEntities()
            : base("name=TiDiHuiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AdminLog> AdminLog { get; set; }
        public virtual DbSet<BrandImprove> BrandImprove { get; set; }
        public virtual DbSet<BUser> BUser { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CBGToB> CBGToB { get; set; }
        public virtual DbSet<CommonUser> CommonUser { get; set; }
        public virtual DbSet<CUserEqpt> CUserEqpt { get; set; }
        public virtual DbSet<Distribution> Distribution { get; set; }
        public virtual DbSet<NaturalInfo> NaturalInfo { get; set; }
        public virtual DbSet<ProxyNature_c> ProxyNature_c { get; set; }
        public virtual DbSet<ProxyUser> ProxyUser { get; set; }
        public virtual DbSet<Shop> Shop { get; set; }
        public virtual DbSet<ShopScore> ShopScore { get; set; }
    }
}
